# in _config.yml
title: "Iniciación a las redes neuronales con pyTorch"
logo: images/logo.png
execute:
  execute_notebooks: "off"

repository:
  url: https://github.com/pakitochus/tutorial_pytorch
html:
  use_repository_button: true